version: "1.0"
mode: parallel
stages:
  - prepare
  - unit-test
  - lint
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: prepare
  UnitTests:
    title: Unit test
    stage: unit-test
    image: "golang:1.18"
    commands:
      - go test -v
    when:
      steps:
        - name: main_clone
          on:
            - success
  GoLint:
    title: Lint
    stage: lint
    image: "golangci/golangci-lint:v1.45.2"
    commands:
      - golangci-lint run
    when:
      steps:
        - name: main_clone
          on:
            - success
