version: "1.0"
mode: parallel
stages:
  - prepare
  - unit-test
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: prepare
  UnitTests:
    title: Unit test
    stage: unit-test
    image: "golang:1.18"
    commands:
      - go test -v
    when:
      steps:
        - name: main_clone
          on:
            - success
