version: "1.0"
stages:
  - prepare
  - build
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: prepare
  AppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: ${{CF_REPO_NAME}}
    working_directory: ./
    tag: modules
    dockerfile: Dockerfile
    disable_push: 'match("${{CF_BRANCH}}", "master", false) == false'
