version: "1.0"
stages:
  - prepare
  - build
  - release
steps:
  main_clone:
    title: "Cloning main repository..."
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    stage: prepare

  BuildApp:
    title: Compiling go code
    stage: build
    image: "golang:1.18"
    commands:
      - go build

  ReleaseApp: # requires that GITHUB_TOKEN is set as an encrypted variable in CodeFresh (scope: repo)
    title: Creating packages
    stage: release
    image: "goreleaser/goreleaser"
    commands:
      - goreleaser --rm-dist
